[package]
name = "shuttle_jvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cafebabe = "0.6.1"
once_cell = "1.18.0"